### ISSUE TITLE
Creating the infrastructure for an Order Book in C++

### ISSUE THREAD

**Issue by d4jl** [Massssssi/COMP5530M#1]
+ Aim is to get the basic code for an order book implemented in C++
+ Requires background research to understand how an order book is structured, and the matching algorithms which are used in an order book. Also, need to decide the granularity we will use for this order book.

**Comment by shreyashonnalli** [comment]
https://www.youtube.com/watch?v=fxN4xEZvrxI&list=PL8nBmR5eGh34AynaXik3rgiW3qK6FKXVq&index=16

How to code an orderbook in cpp^

**Comment by shreyashonnalli** [comment]
https://web.archive.org/web/20110219163448/http://howtohft.wordpress.com/2011/02/15/how-to-build-a-fast-limit-order-book/

Structure of an orderbook
